RING-43206 - Create and Remove offline installer workflows
scality/spark pull request #37
Opened 2023-06-29 00:04 UTC by TrevorBenson

2023-06-29 00:56 UTC, tcarmet reviewed
Did a quick look here, and I believe I need a bit of context in order to give a proper review, if you can tell me:

- What's the goal of each workflow?
- When are those workflow triggered, consistently after each release? Sometimes?
- Are you triggering multiple workflows when making a release?

2023-06-29 22:16 UTC, tcarmet requested changes
Thanks for the context, most of my review are tips just to open our minds a bit, the only change that I think would be required is to tag the repository inside the workflow, so that only one operation is needed to release it. (left the code as suggestion so that it's easy to figure out how to).

2023-06-29 22:16 UTC, tcarmet commented on .github/workflows/create-offline-installer.yml
> +          export staging_archive=spark-offline-archive-prerelease.run
Usually even when there's a prerelease, a tag is made, so it's better to include it.
```suggestion
          export staging_archive=spark-offline-archive-${{ inputs.tag }}-prerelease.run
```

2023-06-29 22:16 UTC, tcarmet commented on .github/workflows/remove-offline-installer.yml
> +name: Remove Tagged Offline Installer
Honestly I wouldn't remove them, and keep those release as long as required, you never know when you might need an old release and having all of them available really helps, you can always keep a symlink to the latest one if needed. But all of this depends on your context so it's really up to you.

2023-06-29 22:16 UTC, tcarmet commented on .github/workflows/remove-offline-installer.yml
> +  workflow_dispatch:
Adding a [schedule](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule) to this workflow might fit. If the workflow wouldn't require any `inputs`. Like listing all the releases and removing x, y, z depending on some criteria. 
```suggestion
on:
  schedule:
    - cron:  '30 5,17 * * *'
  workflow_dispatch:
```

2023-06-29 22:16 UTC, tcarmet commented on .github/workflows/create-offline-installer.yml
> +          scp ${{ env.temp_path }}/../${{ env.staging_archive }} ${{ secrets.PACKAGES_SSH_USER }}@packages:/mnt/cephstorage/www/html/packages/extras/centos/7/x86_64/scality/
I understand why you have the `staging_archive` path, but `temp_path` shouldn't be needed. The repository is cloned on `${{ github.workspace }}` or `${{ env.GITHUB_WORKSPACE }}` you can use that as a base path if needed.

2023-06-29 22:16 UTC, tcarmet commented on .github/workflows/create-offline-installer.yml
>          default: false
A lot of those variables (maybe not all, but most of them), can be set directly as environment variable either at the workflow level or at the job level.

```yaml

env:
  # those I'm sure they work
  image_path: 'spark-dev/deployment'
  # those not entirely sure but worth the shot.
  staging_archive: spark-offline-archive-${{ inputs.tag }}${{ if inputs.prerelease '-prerelease' else '' }}.run
```

2023-06-30 19:25 UTC, TrevorBenson commented on .github/workflows/create-offline-installer.yml
>          default: false
* `if` results in unrecognized name-value.
* Removing `if` it results in `'-prerelease'` being an unexpected symbol.
* `else` doesn't appear to be an option along with github `if` conditions

I was hoping my prior tests were invalid, but I still don't seem to be able to use the latter syntax under `env` sections. I'll use the same logic and use `GITHUB_ENV`.

2023-06-30 19:27 UTC, TrevorBenson commented on .github/workflows/create-offline-installer.yml
> +          scp ${{ env.temp_path }}/../${{ env.staging_archive }} ${{ secrets.PACKAGES_SSH_USER }}@packages:/mnt/cephstorage/www/html/packages/extras/centos/7/x86_64/scality/
Agreed. I'll remove it and retest. Once this PR is cleaned up I'll re-request review.

Thanks

2023-06-30 20:14 UTC, TrevorBenson commented on .github/workflows/create-offline-installer.yml
> +        if: ${{ inputs.prerelease }}
@tcarmet This is that 3.xGB release file which is too large for stock GitHub. I could potentially use LFS in this repository since it is not the TS `scality-official-tools` where they experienced an LFS issue. 

My current preference is probably to not bother storing in Github, LFS or otherwise, since it would be a 3+GB object every build. However I'm open to it if you think it the cost to benefit ratio is worthwhile.

2023-06-30 20:25 UTC, TrevorBenson commented on .github/workflows/remove-offline-installer.yml
> +name: Remove Tagged Offline Installer
I'll only use this to remove "prerelease" then after I download it into a lab and leave the full GA releases unless we get low on space or IT requests some cleanup.

2023-06-30 20:37 UTC, tcarmet commented on .github/workflows/create-offline-installer.yml
> +        if: ${{ inputs.prerelease }}
It's not about storing the release artifacts into the release itself, but merely doing the tag of the repository in the workflow.

2023-06-30 20:42 UTC, tcarmet commented on .github/workflows/create-offline-installer.yml
>          default: false
Ah yes, indeed, pretty sure I did something like this in the past, might have been something like this then:
```yaml
env:
  staging_archive: spark-offline-archive-${{ inputs.tag }}${{ inputs.prerelease == true && '-prerelease' || '' }}.run
```

But I would say don't bother with it, what you did is easier to understand at this point lol.

2023-06-30 20:43 UTC, tcarmet commented on .github/workflows/create-offline-installer.yml
> +        if: ${{ inputs.prerelease }}
In other words, you won't be storing any big files.

2023-06-30 20:48 UTC, TrevorBenson commented on .github/workflows/create-offline-installer.yml
> +        if: ${{ inputs.prerelease }}
@tcarmet This is that 3.xGB release file. I could use LFS in this repository since it is not the TS `scality-official-tools` repo where they experienced an LFS issue.

My current preference is probably to not bother storing in Github, LFS or otherwise, since it would be a 3+GB object every build and it is being stored on packages.scality.com. However I'm open to it if you think it the cost to benefit ratio is worthwhile for something this large which could be rebuilt via the tags when needed.

2023-06-30 20:59 UTC, TrevorBenson commented on .github/workflows/create-offline-installer.yml
>          default: false
Hah, I may leave this as it is, however I definitely will add this to a branch in my `trevorbenson/itsatest` repo, my cheatsheet to stop searching docs and stackexchange for specific ways to implement things.

2023-06-30 21:10 UTC, TrevorBenson commented on .github/workflows/create-offline-installer.yml
>          default: false
Winner! I had thought about swapping `if` to `==` but then didn't think aobut symbols vs. `else`. Love it.

2023-06-30 21:27 UTC, TrevorBenson commented on .github/workflows/create-offline-installer.yml
> +        if: ${{ inputs.prerelease }}
Deleted the double post, not sure how that happened.

2023-06-30 21:28 UTC, TrevorBenson commented on .github/workflows/create-offline-installer.yml
> +        if: ${{ inputs.prerelease }}
Ahh. I overlooked the missing `files:`. :+1:

2023-06-30 21:59 UTC, tcarmet commented on .github/workflows/create-offline-installer.yml
>          default: false
👌

2023-06-30 22:34 UTC, tcarmet requested changes

2023-06-30 22:34 UTC, tcarmet commented on .github/workflows/release.yml
> +          ref: ${{ inputs.tag }}
At this point, the tag does not exist, leaving the default value will clone the given branch on the workflow_dispatch and tag the latest commit thanks to the last step you added. 
```suggestion
      - name: Checkout
        uses: actions/checkout@v3
```

2023-06-30 22:34 UTC, tcarmet commented on .github/workflows/release.yml
> +  staging_path: /home/runner/work/spark/spark/staging
```suggestion
  staging_path: ${{ github.workspace }}/staging
```

2023-07-01 00:27 UTC, tcarmet approved these changes
I'll be out on PTO next week, the PR LGTM assuming the two suggestions:
- [here](https://github.com/scality/spark/pull/37/files#r1248322026)
- [and here](https://github.com/scality/spark/pull/37/files#r1248321456)

Are taken into account.

2023-07-05 15:35 UTC, TrevorBenson commented on .github/workflows/release.yml
> +          ref: ${{ inputs.tag }}
The input is gathered during worfklow_dispatch so should exist prior to checkout.

I presume this meant that the input tag would not exist **after** implementing the suggested code to release on each PR merge?

2023-07-10 20:05 UTC, tcarmet commented on .github/workflows/release.yml
> +          ref: ${{ inputs.tag }}
I think what you're saying is correct but I'm gonna refrase it just in case.

The value inside the `input.tag` will exist, but the tag itself on the repository, no.

2023-09-21 17:42 UTC, merged