RING-46131 Add new reverse lookup script s3_fsck_p2_revlookup.py
scality/spark pull request #50
Opened 2024-03-31 20:11 UTC by scality-fno

- add new reverse lookup script `s3_fsck_p2_reverselookup.py`: 
  - in the output of p2, look the supposed orphaned keys up: 
    - if the service ID found in the lookup matches `/4[CD]/` (SPLIT), look further for the top input key, 
    - else: print the found input key
 
- add cosmetic changes to the `config.yml` template
- define the SHELL in the `submit.py` 

More on the context here: https://scality.atlassian.net/wiki/spaces/~696793679/pages/2323054719/Spark+usage+hunt+S3+orphans+down.#4.1.2-%E2%9A%99%EF%B8%8F-%F0%9F%AA%84--automated-approach

2024-04-02 10:58 UTC, scality-gdoumergue requested changes
I understand that the code needs to ssh to localhost, in order to "get out" of the Docker container and use the nasdk tools.
Couldn't we have a way to embark scality's Python SDK and use it instead of ssh+binaries?

2024-04-02 12:08 UTC, scality-fno commented
> I understand that the code needs to ssh to localhost, in order to "get out" of the Docker container and use the nasdk tools. Couldn't we have a way to embark scality's Python SDK and use it instead of ssh+binaries?
💡 
Yes, why not. At this stage, I'm not sure how to achieve this, though.
I was told we could also map the proper volumes so the container can reach them, but that's not guaranteed to work fully, because of potential differences between the host's OS (RHEL flavour) and the container's OS (Alpine).

2024-04-04 12:40 UTC, borisfaure approved these changes

2024-04-04 12:40 UTC, borisfaure commented on scripts/S3_FSCK/s3_fsck_p2_reverselookup.py
> +        cmd = "ssh -qT $(hostname -i) {} -b '{}' -d '{}' {} 2>/dev/null | strings | awk '/index/{{$1=substr($1,length($1)-39,40); print}}'".format(SPLITGETUSERMD_BIN, ip_port, ARCDATA_DRIVER, key)
```suggestion
        cmd = "ssh -qT $(hostname -i) {} -b '{}' -d '{}' {} 2>/dev/null | strings -t binary -a | awk '/index/{{$1=substr($1,length($1)-39,40); print}}'".format(SPLITGETUSERMD_BIN, ip_port, ARCDATA_DRIVER, key)
```
otherwise strings may try to be too smart and do weird stuff

2024-04-04 12:50 UTC, scality-fno commented on scripts/S3_FSCK/s3_fsck_p2_reverselookup.py
> +        cmd = "ssh -qT $(hostname -i) {} -b '{}' -d '{}' {} 2>/dev/null | strings | awk '/index/{{$1=substr($1,length($1)-39,40); print}}'".format(SPLITGETUSERMD_BIN, ip_port, ARCDATA_DRIVER, key)
Hmm, thanks for the heads up. I've just tried it and the shell complains: 

```bash
scalsplitgetusermd -b 10.4.12.21:4244 -d arcdata 0014CF2744580F1F0AA8DF00000000511470C070 | strings -t binary -a
Usage: strings [option(s)] [file(s)]
 Display printable strings in [file(s)] (stdin by default)
 The options are:
  -a - --all                Scan the entire file, not just the data section [default]
  -d --data                 Only scan the data sections in the file
  -f --print-file-name      Print the name of the file before each string
  -n --bytes=[number]       Locate & print any NUL-terminated sequence of at
  -<number>                   least [number] characters (default 4).
  -t --radix={o,d,x}        Print the location of the string in base 8, 10 or 16
  -w --include-all-whitespace Include all whitespace as valid string characters
  -o                        An alias for --radix=o
  -T --target=<BFDNAME>     Specify the binary file format
  -e --encoding={s,S,b,l,B,L} Select character size and endianness:
                            s = 7-bit, S = 8-bit, {b,l} = 16-bit, {B,L} = 32-bit
  --unicode={default|show|invalid|hex|escape|highlight}
  -U {d|s|i|x|e|h}          Specify how to treat UTF-8 encoded unicode characters
  -s --output-separator=<string> String used to separate strings in output.
  @<file>                   Read options from <file>
  -h --help                 Display this information
  -v -V --version           Print the program's version number
strings: supported targets: elf64-x86-64 elf32-i386 elf32-iamcu elf32-x86-64 a.out-i386-linux pei-i386 pei-x86-64 elf64-l1om elf64-k1om elf64-little elf64-big elf32-little elf32-big plugin srec symbolsrec verilog tekhex binary ihex
write: Broken pipe
write usermd failed
[Exit 1]
```

2024-04-04 13:31 UTC, scality-fno commented on scripts/S3_FSCK/s3_fsck_p2_reverselookup.py
> +        cmd = "ssh -qT $(hostname -i) {} -b '{}' -d '{}' {} 2>/dev/null | strings | awk '/index/{{$1=substr($1,length($1)-39,40); print}}'".format(SPLITGETUSERMD_BIN, ip_port, ARCDATA_DRIVER, key)
Maybe you meant `-T binary` instead :)

2024-05-28 09:46 UTC, merged